/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNotification: typeof import('./src/components/AppNotification.vue')['default']
    AppNotifications: typeof import('./src/components/AppNotifications.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseEmpty: typeof import('./src/components/BaseEmpty.vue')['default']
    BaseError: typeof import('./src/components/BaseError.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    IconLucideCircleAlert: typeof import('~icons/lucide/circle-alert')['default']
    IconLucideCog: typeof import('~icons/lucide/cog')['default']
    IconLucideLogIn: typeof import('~icons/lucide/log-in')['default']
    IconLucideLogOut: typeof import('~icons/lucide/log-out')['default']
    IconLucideMap: typeof import('~icons/lucide/map')['default']
    IconLucidePencilRuler: typeof import('~icons/lucide/pencil-ruler')['default']
    IconLucidePlus: typeof import('~icons/lucide/plus')['default']
    IconLucideRefreshCw: typeof import('~icons/lucide/refresh-cw')['default']
    IconLucideSave: typeof import('~icons/lucide/save')['default']
    IconLucideTrash: typeof import('~icons/lucide/trash')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    IconLucideUserCog: typeof import('~icons/lucide/user-cog')['default']
    IconLucideUserRoundCog: typeof import('~icons/lucide/user-round-cog')['default']
    PlanForm: typeof import('./src/components/PlanForm.vue')['default']
    PlanListItem: typeof import('./src/components/PlanListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
